name: ElasticSearch Batch Job

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  batch-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build And Push
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker build -f es.Dockerfile -t skku-es-batch .
          docker tag skku-es-batch sinkyoungdeok/skku-es-batch
          docker push sinkyoungdeok/skku-es-batch
      - name: Deploy Prod
        uses: appleboy/ssh-action@v0.1.4
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST_NAME }}
          username: ubuntu
          port: 22
          script: |
            docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
            docker pull sinkyoungdeok/skku-es-batch

            docker run --net ubuntu_default sinkyoungdeok/skku-es-batch